config/routes.rb
Rails.application.routes.draw do
  require 'sidekiq/web'
  mount Sidekiq::Web => '/sidekiq'
  devise_for :users
  root 'contacts#index'
  resources :contacts, only: [:index, :create, :new]
  resources :csv_import do
    collection { post :import }
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
  belongs_to :user
  before_validation :set_cc_franchise_name, :set_cc_last_four_digits
  after_validation :encrypt_cc_number, on: :create

  REGEX_NAME = /\A[^0-9`!@#\$%\^&*+_=]+\z/.freeze
  REGEX_MAIL = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i.freeze

  validates_format_of :name, with: REGEX_NAME,
                      message: "only allows letters and coumpound names with '-'"
  validates_format_of :email, with: REGEX_MAIL,
                      message: "only allows valid emails"

  validates :name, :email, :birth_date, :address, :phone,
            :credit_card, :franchise, :cc_last_digits, presence: true

  validates :name, length: { minimum: 2 }


  private
  def set_cc_franchise_name
    franchise_name = CreditCardValidations::Detector.new(self.credit_card).brand_name
    self.franchise = franchise_name
  end

  def set_cc_last_four_digits
    self.cc_last_digits = self.credit_card[-4..-1]
  end

  def encrypt_cc_number
    self.credit_card = BCrypt::Password.create(self.credit_card)
  end


end

app/models/csv_import.rb
class CsvImport < ApplicationRecord
  belongs_to :user
  attribute :status, :string, default: "on_hold"
  enum status: { on_hold: "on_hold" , processing: "processing",
                 failed: "failed" , finished: "finished" }, _default: "on_hold"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :contacts, dependent: :destroy
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  before_action :authenticate_user!

  def index
    @contacts = Contact.where(user_id: current_user.id)
  end

  def new
    @contact = Contact.new
  end

  def create
    @contact = current_user.contacts.build(contact_params)
    if @contact.save
      redirect_to contacts_path, status: :created, notice: "The contact has been created."
    else
      render new_contact_path, status: :unprocessable_entity
    end

  end


  private
  def contact_params
    params.require(:contact).permit(:name ,:birth_date, :phone, :address ,
                                    :credit_card, :franchise, :cc_last_digits, :email)
  end
end

app/controllers/csv_import_controller.rb
class CsvImportController < ApplicationController
  before_action :authenticate_user!
  before_action :set_csv_import, only: [:update]

  def index
    @csv_imports = CsvImport.where(user_id: current_user.id)
  end

  def new
    @csv_import = CsvImport.new
  end

  def create
    @csv_import = current_user.user.build(csv_import_params)
  end

  def update
    @csv_import.update(csv_import_params)
  end

  def import
    if params[:file].nil?
      redirect_to new_csv_import_path, alert: "Please choose a file to import"
    else
      file_path_to_save_to = './tmp/' + params[:file].original_filename
      File.write(file_path_to_save_to, params[:file].read)
      ImportCsvFileJob.perform_later(file_path_to_save_to, params[:file].original_filename, current_user)
      redirect_to contacts_path, notice: "CSV imported successfully"
    end
  end

  private
  def set_csv_import
    @csv_import = CsvImport.find(params[:id])
  end

  def csv_import_params
    params.require(:csv_import).permit(:filename, :status, :user_id)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/csv_import_helper.rb
module CsvImportHelper
end

app/views/contacts/index.html.erb
<h1>Contacts List</h1>
<p style="color: green"><%= notice %></p>
<section>
  <table>
    <thead>
    <tr>
      <th>Name</th>
      <th>Date of Birth</th>
      <th>Phone</th>
      <th>Address</th>
      <th>Credit Card(Last Digits)</th>
      <th>Franchise</th>
      <th>Email</th>
    </tr>
    </thead>
    <tbody>
    <% @contacts.each do |contact| %>
      <tr>
        <td><%= contact.name %></td>
        <td><%= contact.birth_date.strftime("%Y %B %d") %></td>
        <td><%= contact.phone %></td>
        <td><%= contact.address %></td>
        <td><%= contact.cc_last_digits %></td>
        <td><%= contact.franchise %></td>
        <td><%= contact.email %></td>
      </tr>
      </tbody>
    <% end %>
    </table>
</section>

app/views/contacts/new.html.erb
<h1>New Contact</h1>
<%= form_for @contact do | form | %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div>
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div>
    <%= form.label :birth_date %>
    <%= form.date_field :birth_date %>
  </div>

  <div>
    <%= form.label :phone %>
    <%= form.text_field :phone %>
  </div>

  <div>
    <%= form.label :address %>
    <%= form.text_field :address %>
  </div>

  <div>
    <%= form.label :credit_card %>
    <%= form.text_field :credit_card %>
  </div>

  <div>
    <%= form.submit %>
  </div>

<% end %>

app/views/csv_import/index.html.erb
<h1>My Import Logs</h1>

<section>
  <table>
    <thead>
    <tr>
      <th>Filename</th>
      <th>Created at</th>
      <th>Status</th>
    </tr>
    </thead>
    <tbody>
    <% @csv_imports.each do |import| %>
      <tr>
        <td><%= import.filename %></td>
        <td><%= import.created_at %></td>
        <td><%= import.status %></td>
      </tr>
      </tbody>
    <% end %>
    </table>
</section>

app/views/csv_import/new.html.erb
<h1>Import CSV</h1>
<%= form_tag import_csv_import_index_path, multipart: true do%>
  <%= file_field_tag :file %>
  <%= submit_tag "Import CSV" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Contacts Importer</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.simplecss.org/simple.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <nav>
      <% if user_signed_in? %>
        <%= link_to 'Home', contacts_path %> |
        <%= link_to 'Add Contact Manually', new_contact_path %> |
        <%= link_to 'Import CSV', new_csv_import_path %> |
        <%= link_to 'My Import Logs', csv_import_index_path %> |
        <%= link_to 'Logout', destroy_user_session_path, method: :delete%>
      <% end %>
    </nav>
    <main>
      <%= yield %>
    </main>
  </body>
</html>